<?php
/**
 * @file
 * Code for the DIYCHI Events feature.
 */

include_once('diychi_events.features.inc');

/**
* Implementation of hook_services_resources().
*/
function diychi_events_services_resources() {
  return array(
    'bands' => array(
      'index' => array(
        'help' => 'Retrieves a listing of bands',
        'file' => array('type' => 'inc', 'module' => 'diychi_events', 'name' => 'resources/bands_resource'),
        'callback' => '_bands_resource_index',
        'args' => array(
          array(
            'name' => 'page',
            'optional' => TRUE,
            'type' => 'int',
            'description' => 'The zero-based index of the page to get, defaults to 0.',
            'default value' => 0,
            'source' => array('param' => 'page'),
          ),
          array(
            'name' => 'fields',
            'optional' => TRUE,
            'type' => 'string',
            'description' => 'The fields to get.',
            'default value' => '*',
            'source' => array('param' => 'fields'),
          ),
          array(
            'name' => 'parameters',
            'optional' => TRUE,
            'type' => 'array',
            'description' => 'Parameters array',
            'default value' => array(),
            'source' => array('param' => 'parameters'),
          ),
          array(
            'name' => 'pagesize',
            'optional' => TRUE,
            'type' => 'init',
            'description' => 'Number of records to get per page.',
            'default value' => variable_get('services_node_index_page_size', 20),
            'source' => array('param' => 'pagesize'),
          ),
        ),
        'access arguments' => array('access content'),
      ),
    ),
  );
}
